// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawler/resources.proto

package crawler

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Major struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Major) Reset()         { *m = Major{} }
func (m *Major) String() string { return proto.CompactTextString(m) }
func (*Major) ProtoMessage()    {}
func (*Major) Descriptor() ([]byte, []int) {
	return fileDescriptor_b95cd700fb69a1c6, []int{0}
}

func (m *Major) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Major.Unmarshal(m, b)
}
func (m *Major) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Major.Marshal(b, m, deterministic)
}
func (m *Major) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Major.Merge(m, src)
}
func (m *Major) XXX_Size() int {
	return xxx_messageInfo_Major.Size(m)
}
func (m *Major) XXX_DiscardUnknown() {
	xxx_messageInfo_Major.DiscardUnknown(m)
}

var xxx_messageInfo_Major proto.InternalMessageInfo

func (m *Major) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Major) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Major) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*Major)(nil), "crawler.Major")
}

func init() {
	proto.RegisterFile("crawler/resources.proto", fileDescriptor_b95cd700fb69a1c6)
}

var fileDescriptor_b95cd700fb69a1c6 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8d, 0x3d, 0x0b, 0xc2, 0x30,
	0x10, 0x40, 0x69, 0xeb, 0x07, 0x66, 0x10, 0xc9, 0x62, 0x46, 0x71, 0x12, 0x91, 0x66, 0x70, 0x76,
	0x71, 0x77, 0x71, 0x74, 0xbb, 0x7c, 0xa8, 0x27, 0x69, 0xae, 0x5c, 0x12, 0xfc, 0xfb, 0x62, 0xe8,
	0xf6, 0x78, 0x6f, 0x78, 0x62, 0x6b, 0x19, 0xbe, 0xc1, 0xb3, 0x66, 0x9f, 0xa8, 0xb0, 0xf5, 0xa9,
	0x1f, 0x99, 0x32, 0xc9, 0xe5, 0x14, 0xf6, 0x17, 0x31, 0xbf, 0xc1, 0x87, 0x58, 0xae, 0x45, 0x8b,
	0x4e, 0x35, 0xbb, 0xe6, 0xb0, 0xba, 0xb7, 0xe8, 0xa4, 0x14, 0xb3, 0x08, 0x83, 0x57, 0x6d, 0x35,
	0x95, 0xe5, 0x46, 0x74, 0x85, 0x83, 0xea, 0xaa, 0xfa, 0xe3, 0xf5, 0xf4, 0x38, 0xbe, 0x30, 0xbf,
	0x8b, 0xe9, 0x2d, 0x0d, 0x7a, 0x04, 0x13, 0x28, 0x33, 0x46, 0x74, 0xe0, 0xf4, 0xd3, 0xa2, 0x8f,
	0x16, 0x21, 0xe9, 0x69, 0x66, 0x16, 0x75, 0x7e, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x33, 0x1e,
	0xb0, 0xfb, 0x97, 0x00, 0x00, 0x00,
}
