// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/crawler/resources.proto

package crawler

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Major struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Major) Reset()         { *m = Major{} }
func (m *Major) String() string { return proto.CompactTextString(m) }
func (*Major) ProtoMessage()    {}
func (*Major) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff5968e42c14bce, []int{0}
}

func (m *Major) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Major.Unmarshal(m, b)
}
func (m *Major) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Major.Marshal(b, m, deterministic)
}
func (m *Major) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Major.Merge(m, src)
}
func (m *Major) XXX_Size() int {
	return xxx_messageInfo_Major.Size(m)
}
func (m *Major) XXX_DiscardUnknown() {
	xxx_messageInfo_Major.DiscardUnknown(m)
}

var xxx_messageInfo_Major proto.InternalMessageInfo

func (m *Major) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Major) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Major) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Program struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Major                string   `protobuf:"bytes,2,opt,name=major,proto3" json:"major,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Year                 uint32   `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Url                  string   `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Program) Reset()         { *m = Program{} }
func (m *Program) String() string { return proto.CompactTextString(m) }
func (*Program) ProtoMessage()    {}
func (*Program) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff5968e42c14bce, []int{1}
}

func (m *Program) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Program.Unmarshal(m, b)
}
func (m *Program) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Program.Marshal(b, m, deterministic)
}
func (m *Program) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Program.Merge(m, src)
}
func (m *Program) XXX_Size() int {
	return xxx_messageInfo_Program.Size(m)
}
func (m *Program) XXX_DiscardUnknown() {
	xxx_messageInfo_Program.DiscardUnknown(m)
}

var xxx_messageInfo_Program proto.InternalMessageInfo

func (m *Program) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Program) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *Program) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Program) GetYear() uint32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Program) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*Major)(nil), "crawler.Major")
	proto.RegisterType((*Program)(nil), "crawler.Program")
}

func init() {
	proto.RegisterFile("server/crawler/resources.proto", fileDescriptor_eff5968e42c14bce)
}

var fileDescriptor_eff5968e42c14bce = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xbf, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0xc9, 0x2f, 0x0f, 0x07, 0x14, 0x59, 0x2c, 0xb6, 0x92, 0xe3, 0xaa, 0xab, 0x6e, 0x91,
	0xd4, 0x36, 0xf6, 0x82, 0xa4, 0xb4, 0x9b, 0xec, 0x8e, 0x71, 0x24, 0x9b, 0x0d, 0xb3, 0x89, 0xe2,
	0x7f, 0x2f, 0x59, 0x63, 0x50, 0xae, 0xfb, 0xe6, 0x0d, 0x7c, 0x8f, 0x07, 0x77, 0x91, 0xe4, 0x83,
	0xc4, 0x58, 0xc1, 0xcf, 0x9e, 0xc4, 0x08, 0xc5, 0x30, 0x8b, 0xa5, 0x78, 0x1a, 0x25, 0x4c, 0x41,
	0xed, 0xd6, 0xc7, 0xe1, 0x01, 0xaa, 0x27, 0x7c, 0x0f, 0xa2, 0xae, 0x21, 0x67, 0xa7, 0xb3, 0x7d,
	0x76, 0xbc, 0x6c, 0x72, 0x76, 0x4a, 0x41, 0x39, 0xa0, 0x27, 0x9d, 0xa7, 0x24, 0xb1, 0xba, 0x81,
	0x62, 0x96, 0x5e, 0x17, 0x29, 0x5a, 0xf0, 0xc0, 0xb0, 0x7b, 0x96, 0xd0, 0x09, 0xfa, 0x33, 0xc1,
	0x2d, 0x54, 0x7e, 0x31, 0xaf, 0x86, 0x9f, 0x63, 0xd3, 0x16, 0x7f, 0xb4, 0x0a, 0xca, 0x2f, 0x42,
	0xd1, 0xe5, 0x3e, 0x3b, 0x5e, 0x35, 0x89, 0x7f, 0xab, 0xaa, 0xad, 0xea, 0xb1, 0x7e, 0xb9, 0xef,
	0x78, 0x7a, 0x9b, 0xdb, 0x93, 0x0d, 0xde, 0x8c, 0xd8, 0xf6, 0x61, 0x12, 0x1e, 0xd8, 0xa1, 0x33,
	0xaf, 0x96, 0x69, 0xb0, 0x8c, 0xd1, 0xfc, 0xdf, 0xdd, 0x5e, 0xa4, 0xb9, 0xf5, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x10, 0x42, 0xc5, 0x64, 0x10, 0x01, 0x00, 0x00,
}
