// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/crawler/service.proto

package crawler

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListMajorsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMajorsRequest) Reset()         { *m = ListMajorsRequest{} }
func (m *ListMajorsRequest) String() string { return proto.CompactTextString(m) }
func (*ListMajorsRequest) ProtoMessage()    {}
func (*ListMajorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e5438f3339223c8, []int{0}
}

func (m *ListMajorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMajorsRequest.Unmarshal(m, b)
}
func (m *ListMajorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMajorsRequest.Marshal(b, m, deterministic)
}
func (m *ListMajorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMajorsRequest.Merge(m, src)
}
func (m *ListMajorsRequest) XXX_Size() int {
	return xxx_messageInfo_ListMajorsRequest.Size(m)
}
func (m *ListMajorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMajorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMajorsRequest proto.InternalMessageInfo

type ListMajorsResponse struct {
	Majors               []*Major `protobuf:"bytes,1,rep,name=majors,proto3" json:"majors,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMajorsResponse) Reset()         { *m = ListMajorsResponse{} }
func (m *ListMajorsResponse) String() string { return proto.CompactTextString(m) }
func (*ListMajorsResponse) ProtoMessage()    {}
func (*ListMajorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e5438f3339223c8, []int{1}
}

func (m *ListMajorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMajorsResponse.Unmarshal(m, b)
}
func (m *ListMajorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMajorsResponse.Marshal(b, m, deterministic)
}
func (m *ListMajorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMajorsResponse.Merge(m, src)
}
func (m *ListMajorsResponse) XXX_Size() int {
	return xxx_messageInfo_ListMajorsResponse.Size(m)
}
func (m *ListMajorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMajorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMajorsResponse proto.InternalMessageInfo

func (m *ListMajorsResponse) GetMajors() []*Major {
	if m != nil {
		return m.Majors
	}
	return nil
}

func (m *ListMajorsResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*ListMajorsRequest)(nil), "crawler.ListMajorsRequest")
	proto.RegisterType((*ListMajorsResponse)(nil), "crawler.ListMajorsResponse")
}

func init() {
	proto.RegisterFile("server/crawler/service.proto", fileDescriptor_3e5438f3339223c8)
}

var fileDescriptor_3e5438f3339223c8 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0x3d, 0x4f, 0x03, 0x31,
	0x0c, 0x55, 0x41, 0x14, 0x61, 0x04, 0x12, 0x81, 0xa1, 0x3a, 0x10, 0xaa, 0x3a, 0xa0, 0x4e, 0x89,
	0x68, 0xff, 0x01, 0x15, 0x4c, 0xb0, 0x64, 0x64, 0xcb, 0xe5, 0x0c, 0x04, 0xdd, 0xc5, 0x87, 0x9d,
	0xc0, 0xdf, 0x47, 0x5c, 0x4e, 0x7c, 0x8f, 0xef, 0xc3, 0xcf, 0xcf, 0x86, 0x33, 0x41, 0x7e, 0x45,
	0x36, 0x9e, 0xdd, 0x5b, 0x8b, 0x6c, 0x3e, 0x60, 0xf0, 0xa8, 0x7b, 0xa6, 0x44, 0x6a, 0x77, 0xa4,
	0xab, 0xf3, 0x5f, 0x36, 0x46, 0xa1, 0xcc, 0x1e, 0xa5, 0x18, 0x17, 0xc7, 0x70, 0x74, 0x1b, 0x24,
	0xdd, 0xb9, 0x67, 0x62, 0xb1, 0xf8, 0x92, 0x51, 0xd2, 0xc2, 0x82, 0xfa, 0x4e, 0x4a, 0x4f, 0x51,
	0x50, 0x5d, 0xc0, 0xb4, 0x1b, 0x98, 0xd9, 0x64, 0xbe, 0xbd, 0xdc, 0x5f, 0x1d, 0xea, 0x31, 0x54,
	0x0f, 0x46, 0x3b, 0xaa, 0xea, 0x04, 0x76, 0x3c, 0xe5, 0x98, 0x66, 0x5b, 0xf3, 0xc9, 0xf2, 0xc0,
	0x16, 0xb0, 0xb2, 0xb0, 0x77, 0xb3, 0xd9, 0x94, 0x01, 0x75, 0x0d, 0xf0, 0xb5, 0x40, 0x55, 0x9f,
	0x41, 0x7f, 0xaa, 0x54, 0xa7, 0xff, 0x6a, 0xa5, 0xd1, 0xd5, 0xfa, 0xfe, 0xf2, 0x31, 0xa4, 0xa7,
	0x5c, 0x6b, 0x4f, 0x9d, 0xe9, 0x5d, 0xdd, 0x52, 0xe2, 0x10, 0x43, 0xe3, 0x1a, 0xf3, 0xe0, 0x03,
	0x46, 0x1f, 0x9c, 0x98, 0x9f, 0x1f, 0xa8, 0xa7, 0xc3, 0xe1, 0xeb, 0xf7, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xbe, 0xdb, 0x99, 0x6c, 0x41, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FCCrawlerClient is the client API for FCCrawler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FCCrawlerClient interface {
	ListMajors(ctx context.Context, in *ListMajorsRequest, opts ...grpc.CallOption) (*ListMajorsResponse, error)
}

type fCCrawlerClient struct {
	cc grpc.ClientConnInterface
}

func NewFCCrawlerClient(cc grpc.ClientConnInterface) FCCrawlerClient {
	return &fCCrawlerClient{cc}
}

func (c *fCCrawlerClient) ListMajors(ctx context.Context, in *ListMajorsRequest, opts ...grpc.CallOption) (*ListMajorsResponse, error) {
	out := new(ListMajorsResponse)
	err := c.cc.Invoke(ctx, "/crawler.FCCrawler/ListMajors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FCCrawlerServer is the server API for FCCrawler service.
type FCCrawlerServer interface {
	ListMajors(context.Context, *ListMajorsRequest) (*ListMajorsResponse, error)
}

// UnimplementedFCCrawlerServer can be embedded to have forward compatible implementations.
type UnimplementedFCCrawlerServer struct {
}

func (*UnimplementedFCCrawlerServer) ListMajors(ctx context.Context, req *ListMajorsRequest) (*ListMajorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMajors not implemented")
}

func RegisterFCCrawlerServer(s *grpc.Server, srv FCCrawlerServer) {
	s.RegisterService(&_FCCrawler_serviceDesc, srv)
}

func _FCCrawler_ListMajors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMajorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FCCrawlerServer).ListMajors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crawler.FCCrawler/ListMajors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FCCrawlerServer).ListMajors(ctx, req.(*ListMajorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FCCrawler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crawler.FCCrawler",
	HandlerType: (*FCCrawlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMajors",
			Handler:    _FCCrawler_ListMajors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/crawler/service.proto",
}
