// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/crawler/service.proto

package crawler

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListMajorsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMajorsRequest) Reset()         { *m = ListMajorsRequest{} }
func (m *ListMajorsRequest) String() string { return proto.CompactTextString(m) }
func (*ListMajorsRequest) ProtoMessage()    {}
func (*ListMajorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e5438f3339223c8, []int{0}
}

func (m *ListMajorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMajorsRequest.Unmarshal(m, b)
}
func (m *ListMajorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMajorsRequest.Marshal(b, m, deterministic)
}
func (m *ListMajorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMajorsRequest.Merge(m, src)
}
func (m *ListMajorsRequest) XXX_Size() int {
	return xxx_messageInfo_ListMajorsRequest.Size(m)
}
func (m *ListMajorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMajorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMajorsRequest proto.InternalMessageInfo

type ListMajorsResponse struct {
	Majors               []*Major `protobuf:"bytes,1,rep,name=majors,proto3" json:"majors,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMajorsResponse) Reset()         { *m = ListMajorsResponse{} }
func (m *ListMajorsResponse) String() string { return proto.CompactTextString(m) }
func (*ListMajorsResponse) ProtoMessage()    {}
func (*ListMajorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e5438f3339223c8, []int{1}
}

func (m *ListMajorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMajorsResponse.Unmarshal(m, b)
}
func (m *ListMajorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMajorsResponse.Marshal(b, m, deterministic)
}
func (m *ListMajorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMajorsResponse.Merge(m, src)
}
func (m *ListMajorsResponse) XXX_Size() int {
	return xxx_messageInfo_ListMajorsResponse.Size(m)
}
func (m *ListMajorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMajorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMajorsResponse proto.InternalMessageInfo

func (m *ListMajorsResponse) GetMajors() []*Major {
	if m != nil {
		return m.Majors
	}
	return nil
}

func (m *ListMajorsResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ListProgramsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProgramsRequest) Reset()         { *m = ListProgramsRequest{} }
func (m *ListProgramsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProgramsRequest) ProtoMessage()    {}
func (*ListProgramsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e5438f3339223c8, []int{2}
}

func (m *ListProgramsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProgramsRequest.Unmarshal(m, b)
}
func (m *ListProgramsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProgramsRequest.Marshal(b, m, deterministic)
}
func (m *ListProgramsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProgramsRequest.Merge(m, src)
}
func (m *ListProgramsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProgramsRequest.Size(m)
}
func (m *ListProgramsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProgramsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProgramsRequest proto.InternalMessageInfo

type ListProgramsResponse struct {
	Majors               []*ListProgramsResponse_MajorBreakdown `protobuf:"bytes,1,rep,name=majors,proto3" json:"majors,omitempty"`
	Count                uint32                                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *ListProgramsResponse) Reset()         { *m = ListProgramsResponse{} }
func (m *ListProgramsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProgramsResponse) ProtoMessage()    {}
func (*ListProgramsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e5438f3339223c8, []int{3}
}

func (m *ListProgramsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProgramsResponse.Unmarshal(m, b)
}
func (m *ListProgramsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProgramsResponse.Marshal(b, m, deterministic)
}
func (m *ListProgramsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProgramsResponse.Merge(m, src)
}
func (m *ListProgramsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProgramsResponse.Size(m)
}
func (m *ListProgramsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProgramsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProgramsResponse proto.InternalMessageInfo

func (m *ListProgramsResponse) GetMajors() []*ListProgramsResponse_MajorBreakdown {
	if m != nil {
		return m.Majors
	}
	return nil
}

func (m *ListProgramsResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ListProgramsResponse_MajorBreakdown struct {
	Major                *Major     `protobuf:"bytes,1,opt,name=major,proto3" json:"major,omitempty"`
	Programs             []*Program `protobuf:"bytes,2,rep,name=programs,proto3" json:"programs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProgramsResponse_MajorBreakdown) Reset()         { *m = ListProgramsResponse_MajorBreakdown{} }
func (m *ListProgramsResponse_MajorBreakdown) String() string { return proto.CompactTextString(m) }
func (*ListProgramsResponse_MajorBreakdown) ProtoMessage()    {}
func (*ListProgramsResponse_MajorBreakdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e5438f3339223c8, []int{3, 0}
}

func (m *ListProgramsResponse_MajorBreakdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProgramsResponse_MajorBreakdown.Unmarshal(m, b)
}
func (m *ListProgramsResponse_MajorBreakdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProgramsResponse_MajorBreakdown.Marshal(b, m, deterministic)
}
func (m *ListProgramsResponse_MajorBreakdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProgramsResponse_MajorBreakdown.Merge(m, src)
}
func (m *ListProgramsResponse_MajorBreakdown) XXX_Size() int {
	return xxx_messageInfo_ListProgramsResponse_MajorBreakdown.Size(m)
}
func (m *ListProgramsResponse_MajorBreakdown) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProgramsResponse_MajorBreakdown.DiscardUnknown(m)
}

var xxx_messageInfo_ListProgramsResponse_MajorBreakdown proto.InternalMessageInfo

func (m *ListProgramsResponse_MajorBreakdown) GetMajor() *Major {
	if m != nil {
		return m.Major
	}
	return nil
}

func (m *ListProgramsResponse_MajorBreakdown) GetPrograms() []*Program {
	if m != nil {
		return m.Programs
	}
	return nil
}

func init() {
	proto.RegisterType((*ListMajorsRequest)(nil), "crawler.ListMajorsRequest")
	proto.RegisterType((*ListMajorsResponse)(nil), "crawler.ListMajorsResponse")
	proto.RegisterType((*ListProgramsRequest)(nil), "crawler.ListProgramsRequest")
	proto.RegisterType((*ListProgramsResponse)(nil), "crawler.ListProgramsResponse")
	proto.RegisterType((*ListProgramsResponse_MajorBreakdown)(nil), "crawler.ListProgramsResponse.MajorBreakdown")
}

func init() {
	proto.RegisterFile("server/crawler/service.proto", fileDescriptor_3e5438f3339223c8)
}

var fileDescriptor_3e5438f3339223c8 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x51, 0x4f, 0xf2, 0x30,
	0x14, 0x4d, 0xf9, 0x02, 0x9f, 0x5e, 0x95, 0x68, 0xc1, 0x64, 0x99, 0x68, 0x08, 0x31, 0x86, 0x07,
	0xb2, 0x45, 0xf8, 0x07, 0xa0, 0xbe, 0xa8, 0x89, 0xd9, 0xa3, 0x6f, 0xa5, 0xab, 0x58, 0x65, 0xeb,
	0xbc, 0xed, 0xe4, 0xe7, 0xf8, 0xb7, 0xfc, 0x39, 0x86, 0xb5, 0x99, 0x8c, 0x4c, 0x1e, 0x7b, 0xce,
	0xe9, 0x3d, 0xe7, 0x9e, 0x5c, 0xe8, 0x69, 0x81, 0x9f, 0x02, 0x43, 0x8e, 0x6c, 0xb5, 0x14, 0x18,
	0xae, 0x9f, 0x92, 0x8b, 0x20, 0x43, 0x65, 0x14, 0xfd, 0xef, 0x60, 0xff, 0x62, 0x4b, 0x86, 0x42,
	0xab, 0x1c, 0xb9, 0xd0, 0x56, 0x38, 0xe8, 0xc0, 0xc9, 0x83, 0xd4, 0xe6, 0x91, 0xbd, 0x29, 0xd4,
	0x91, 0xf8, 0xc8, 0x85, 0x36, 0x83, 0x08, 0xe8, 0x26, 0xa8, 0x33, 0x95, 0x6a, 0x41, 0xaf, 0xa0,
	0x95, 0x14, 0x88, 0x47, 0xfa, 0xff, 0x86, 0x07, 0xe3, 0x76, 0xe0, 0x86, 0x06, 0x85, 0x30, 0x72,
	0x2c, 0xed, 0x42, 0x93, 0xab, 0x3c, 0x35, 0x5e, 0xa3, 0x4f, 0x86, 0x47, 0x91, 0x7d, 0x0c, 0x4e,
	0xa1, 0xb3, 0x9e, 0xf9, 0x84, 0x6a, 0x81, 0x2c, 0x29, 0xad, 0xbe, 0x09, 0x74, 0xab, 0xb8, 0x73,
	0xbb, 0xd9, 0x72, 0x1b, 0x95, 0x6e, 0x75, 0x72, 0x1b, 0x61, 0x8a, 0x82, 0xbd, 0xc7, 0x6a, 0x95,
	0xee, 0xce, 0xe2, 0xc7, 0xd0, 0xae, 0xea, 0xe9, 0x25, 0x34, 0x8b, 0x1f, 0x1e, 0xe9, 0x93, 0x9a,
	0xd5, 0x2c, 0x49, 0x47, 0xb0, 0x97, 0x39, 0x63, 0xaf, 0x51, 0xa4, 0x3a, 0x2e, 0x85, 0x2e, 0x51,
	0x54, 0x2a, 0xc6, 0x5f, 0x04, 0xf6, 0xef, 0x66, 0x33, 0xcb, 0xd3, 0x5b, 0x80, 0xdf, 0x4e, 0xa9,
	0x5f, 0xd9, 0xa6, 0xd2, 0xbe, 0x7f, 0x56, 0xcb, 0xb9, 0x5a, 0xee, 0xe1, 0x70, 0x73, 0x7f, 0xda,
	0xfb, 0xa3, 0x16, 0x3b, 0xea, 0x7c, 0x67, 0x69, 0xd3, 0xc9, 0xf3, 0xf5, 0x42, 0x9a, 0xd7, 0x7c,
	0x1e, 0x70, 0x95, 0x84, 0x19, 0x9b, 0x2f, 0x95, 0x41, 0x99, 0xca, 0x98, 0xc5, 0xe1, 0x0b, 0x97,
	0x22, 0xe5, 0x92, 0xe9, 0xb0, 0x7a, 0x41, 0xf3, 0x56, 0x71, 0x38, 0x93, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x89, 0x97, 0x23, 0x44, 0x81, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FCCrawlerClient is the client API for FCCrawler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FCCrawlerClient interface {
	// Majors
	ListMajors(ctx context.Context, in *ListMajorsRequest, opts ...grpc.CallOption) (*ListMajorsResponse, error)
	// List programs
	ListPrograms(ctx context.Context, in *ListProgramsRequest, opts ...grpc.CallOption) (*ListProgramsResponse, error)
}

type fCCrawlerClient struct {
	cc grpc.ClientConnInterface
}

func NewFCCrawlerClient(cc grpc.ClientConnInterface) FCCrawlerClient {
	return &fCCrawlerClient{cc}
}

func (c *fCCrawlerClient) ListMajors(ctx context.Context, in *ListMajorsRequest, opts ...grpc.CallOption) (*ListMajorsResponse, error) {
	out := new(ListMajorsResponse)
	err := c.cc.Invoke(ctx, "/crawler.FCCrawler/ListMajors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fCCrawlerClient) ListPrograms(ctx context.Context, in *ListProgramsRequest, opts ...grpc.CallOption) (*ListProgramsResponse, error) {
	out := new(ListProgramsResponse)
	err := c.cc.Invoke(ctx, "/crawler.FCCrawler/ListPrograms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FCCrawlerServer is the server API for FCCrawler service.
type FCCrawlerServer interface {
	// Majors
	ListMajors(context.Context, *ListMajorsRequest) (*ListMajorsResponse, error)
	// List programs
	ListPrograms(context.Context, *ListProgramsRequest) (*ListProgramsResponse, error)
}

// UnimplementedFCCrawlerServer can be embedded to have forward compatible implementations.
type UnimplementedFCCrawlerServer struct {
}

func (*UnimplementedFCCrawlerServer) ListMajors(ctx context.Context, req *ListMajorsRequest) (*ListMajorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMajors not implemented")
}
func (*UnimplementedFCCrawlerServer) ListPrograms(ctx context.Context, req *ListProgramsRequest) (*ListProgramsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPrograms not implemented")
}

func RegisterFCCrawlerServer(s *grpc.Server, srv FCCrawlerServer) {
	s.RegisterService(&_FCCrawler_serviceDesc, srv)
}

func _FCCrawler_ListMajors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMajorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FCCrawlerServer).ListMajors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crawler.FCCrawler/ListMajors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FCCrawlerServer).ListMajors(ctx, req.(*ListMajorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FCCrawler_ListPrograms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProgramsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FCCrawlerServer).ListPrograms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crawler.FCCrawler/ListPrograms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FCCrawlerServer).ListPrograms(ctx, req.(*ListProgramsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FCCrawler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crawler.FCCrawler",
	HandlerType: (*FCCrawlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMajors",
			Handler:    _FCCrawler_ListMajors_Handler,
		},
		{
			MethodName: "ListPrograms",
			Handler:    _FCCrawler_ListPrograms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/crawler/service.proto",
}
